# Alternative compose file for smaller local models
# Usage: docker compose -f compose.yaml -f compose.local-model.yaml up --build

services:
  adk:
    environment:
      # Override to use local model instead of OpenAI
      - AI_DEFAULT_MODEL=local/phi3:mini
      - OPENAI_MODEL_NAME=phi3:mini
    models:
      phi3:
        endpoint_var: MODEL_RUNNER_URL
        model_var: MODEL_RUNNER_MODEL

models:
  phi3:
    # Use smaller model that fits in most systems (3.8B parameters)
    model: ai/phi3:mini-4k-instruct-q4_0
    # Much smaller than Qwen3:14B - only requires ~2GB VRAM
